package gnc1;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class newadmission extends javax.swing.JFrame {
    loaddb db;
    ResultSet rs;

    /**
     * Creates new form newadmission
     */
    public newadmission() {
        initComponents();
        db=new loaddb();
        String qry="select distinct(dept) from courses";
        dept1.addItem("--SELECT--");
        try{
        rs=db.execute(qry);
        while(rs.next())
        {
            dept1.addItem(rs.getString("dept"));
        }
        }
        catch(Exception e)
        {
            System.out.println("Error in newadmission constructor");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cday = new javax.swing.JComboBox();
        cmon = new javax.swing.JComboBox();
        cyear = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        dept1 = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        class1 = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox();
        jComboBox10 = new javax.swing.JComboBox();
        jComboBox11 = new javax.swing.JComboBox();
        jComboBox12 = new javax.swing.JComboBox();
        jComboBox13 = new javax.swing.JComboBox();
        jComboBox14 = new javax.swing.JComboBox();
        jComboBox15 = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel29 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        paddress = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        caddress = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();

        jLabel19.setText("jLabel19");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1024, 750));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 750));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("NEW ADMISSION");
        jLabel2.setPreferredSize(new java.awt.Dimension(67, 161));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(470, 0, 219, 30);

        jLabel3.setText("FIRST NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 40, 140, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 40, 210, 20);

        jLabel4.setText("LAST NAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 70, 150, 14);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(240, 70, 210, 20);

        jLabel5.setText("FATHER NAME");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 100, 150, 16);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(240, 100, 210, 20);

        jLabel6.setText("MOTHER NAME");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 130, 160, 14);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(240, 130, 210, 20);

        jLabel7.setText("DATE OF BIRTH");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 160, 140, 20);

        cday.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdayActionPerformed(evt);
            }
        });
        getContentPane().add(cday);
        cday.setBounds(250, 160, 37, 20);

        cmon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MONTH" }));
        cmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmonActionPerformed(evt);
            }
        });
        getContentPane().add(cmon);
        cmon.setBounds(300, 160, 84, 20);

        cyear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YEAR" }));
        cyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cyearActionPerformed(evt);
            }
        });
        getContentPane().add(cyear);
        cyear.setBounds(390, 160, 51, 20);

        jLabel1.setText("GENDER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 190, 130, 14);

        jLabel8.setText("PERMANENT ADDRESS");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 260, 160, 14);

        jLabel9.setText("CORRESPONDING ADDRESS");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 370, 160, 29);

        jCheckBox1.setText("SAME AS PERMANENT");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(240, 320, 180, 23);

        jLabel10.setText("STUDENT MOBILE NUMBER");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 460, 170, 14);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(230, 460, 230, 20);

        jLabel11.setText("PARENTS MOBILE NUMBER");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(50, 490, 170, 14);

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9);
        jTextField9.setBounds(230, 490, 230, 20);

        jLabel12.setText("EMAIL");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(50, 520, 160, 14);

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField10);
        jTextField10.setBounds(230, 520, 230, 20);

        jLabel13.setText("CASTE");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(50, 550, 170, 14);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT", "GEN", "OBC", "SC" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(230, 550, 118, 20);

        jLabel14.setText("RELIGION");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(50, 580, 170, 16);

        jLabel15.setText("AADHAR CARD NUMBER");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(50, 610, 170, 14);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(230, 610, 230, 20);

        jLabel16.setText("ANNUAL INCOME");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(50, 640, 170, 14);

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField12);
        jTextField12.setBounds(230, 640, 230, 20);

        jLabel17.setText("MODE OF CONVEYANCE");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(50, 670, 170, 14);

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField13);
        jTextField13.setBounds(230, 670, 230, 20);

        jLabel18.setText("DEPARTMENT");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(713, 111, 66, 14);

        dept1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dept1ItemStateChanged(evt);
            }
        });
        dept1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dept1ActionPerformed(evt);
            }
        });
        getContentPane().add(dept1);
        dept1.setBounds(834, 108, 115, 20);

        jLabel20.setText("CLASS");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(713, 139, 31, 14);

        class1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                class1ActionPerformed(evt);
            }
        });
        getContentPane().add(class1);
        class1.setBounds(834, 139, 115, 20);

        jLabel21.setText("SEMESTER");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(713, 173, 51, 14);

        getContentPane().add(jComboBox8);
        jComboBox8.setBounds(834, 170, 115, 20);

        jLabel22.setText("SUBJECT 1");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(713, 208, 52, 14);

        jLabel23.setText("SUBJECT 4");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(713, 287, 52, 14);

        jLabel24.setText("SUBJECT 3");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(713, 260, 52, 14);

        jLabel25.setText("SUBJECT 2");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(713, 235, 52, 14);

        jLabel26.setText("SUBJECT6");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(713, 338, 49, 14);

        jLabel27.setText("SUBJECT 5");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(706, 313, 52, 14);

        getContentPane().add(jComboBox9);
        jComboBox9.setBounds(834, 234, 115, 20);

        getContentPane().add(jComboBox10);
        jComboBox10.setBounds(834, 260, 115, 20);

        getContentPane().add(jComboBox11);
        jComboBox11.setBounds(834, 208, 115, 20);

        jComboBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox12ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox12);
        jComboBox12.setBounds(834, 313, 115, 20);

        jComboBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox13ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox13);
        jComboBox13.setBounds(834, 339, 115, 20);

        getContentPane().add(jComboBox14);
        jComboBox14.setBounds(834, 287, 115, 20);

        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MALE", "FEMALE", "TRANSGENDER" }));
        jComboBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox15ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox15);
        jComboBox15.setBounds(260, 190, 98, 20);

        jLabel28.setText("Are you receving any scolership or apply for scholership ");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(706, 393, 271, 14);

        jRadioButton1.setText("no");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(854, 414, 37, 23);

        jRadioButton2.setText("yes");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(776, 414, 43, 23);

        jLabel29.setText("BANK ACCOUNT NUMBER");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(706, 475, 122, 14);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(858, 472, 244, 20);

        jLabel30.setText("TOTAL FEES");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(706, 533, 59, 14);

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField14);
        jTextField14.setBounds(858, 530, 117, 20);

        paddress.setColumns(20);
        paddress.setRows(5);
        jScrollPane1.setViewportView(paddress);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 220, 344, 96);

        caddress.setColumns(20);
        caddress.setRows(5);
        jScrollPane2.setViewportView(caddress);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(230, 350, 344, 96);

        jLabel31.setText("AMMOUNT PAID");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(706, 576, 78, 14);

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField15);
        jTextField15.setBounds(858, 573, 117, 20);

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 710, 69, 23);

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(610, 710, 71, 23);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(230, 580, 230, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdayActionPerformed

    private void cyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cyearActionPerformed

    private void cmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmonActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        mainmenu mm=new mainmenu();
        mm.setVisible(true);
        this.setVisible(false);
        
                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox15ActionPerformed

    private void jComboBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox12ActionPerformed

    private void jComboBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox13ActionPerformed

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // TODO add your handling code here:
        String ad=paddress.getText();
        caddress.setText(ad);
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void class1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_class1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_class1ActionPerformed

    private void dept1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dept1ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dept1ItemStateChanged

    private void dept1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dept1ActionPerformed
        // TODO add your handling code here:
        class1.removeAllItems();
        String a=""+dept1.getSelectedItem();
        try{
            String qry="select class from courses where dept='"+a+"'";
            class1.addItem("--SELECT--");
            rs=db.execute(qry);
            while(rs.next()){
               class1.addItem(rs.getString("class"));
            }
        }
        catch(Exception e)
        {
            System.out.println("Error in loading class from dept");
        }
    }//GEN-LAST:event_dept1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newadmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newadmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newadmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newadmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newadmission().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea caddress;
    private javax.swing.JComboBox cday;
    private javax.swing.JComboBox class1;
    private javax.swing.JComboBox cmon;
    private javax.swing.JComboBox cyear;
    private javax.swing.JComboBox dept1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboBox13;
    private javax.swing.JComboBox jComboBox14;
    private javax.swing.JComboBox jComboBox15;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextArea paddress;
    // End of variables declaration//GEN-END:variables
}
